# Generated by Django 5.2.10 on 2026-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
