# Generated by Django 5.2.10 on 2026-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_saveditem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='item_type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube'), ('blog', 'Blog/Article'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
