# Generated by Django 5.2.10 on 2026-02-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_saveditem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
